/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Text as HangarText } from '@hangar/web-components/core/Text';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type TextProps = ComponentProps<typeof HangarText>;
