/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Text as HangarText } from '@hangar/web-components/core/Text';
import type { TextProps } from './text.types';

/**
 * WEB wrapper for Text.
 * Pure wrapper with ref forwarding.
 */
const TextComponent = forwardRef<any, TextProps>(
  (props, ref) => {
    return <HangarText ref={ref} {...props} />;
  }
);

TextComponent.displayName = 'Text';

export const Text = memo(TextComponent);
export default Text;
