export const AXIS_HEIGHT = 40;
export const CALCULATED_BAR_COLOR = '#cfcfcf';
export const CALCULATED_BAR_HEIGHT = 14;
export const HEADER_HEIGHT = 44;
export const TIMELINE_TOP_SCROLL_HEIGHT = 16;
export const HEADER_ROW_HEIGHT = HEADER_HEIGHT + TIMELINE_TOP_SCROLL_HEIGHT;
export const PROCESS_COLUMN_WIDTH = 308;
export const REAL_BAR_HEIGHT = 12;
export const ROW_HEIGHT = 68;
export const START_COLUMN_WIDTH = 72;
export const TIME_COLUMN_WIDTH = 72;
export const TIMELINE_ROW_PADDING = 8;
export const LEFT_SCROLLBAR_TOP_OFFSET = 4;
export const TOTAL_LEFT_COLUMNS_WIDTH =
  PROCESS_COLUMN_WIDTH + START_COLUMN_WIDTH + TIME_COLUMN_WIDTH;

export const styles = {
  axisBackground: {
    backgroundColor: '#F2F2F2',
  },
  axisCell: {
    borderLeft: '1px solid #e4e4e4',
    borderBottom: '1px solid #d9d9d9',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    height: HEADER_HEIGHT,
    justifyContent: 'center',
    paddingLeft: 4,
    paddingRight: 4,
  },
  axisContainer: {
    borderBottom: '1px solid #d9d9d9',
    display: 'flex',
    flexDirection: 'column',
    height: HEADER_HEIGHT,
    overflow: 'hidden',
  },
  cellProcess: {
    alignItems: 'flex-start',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    paddingLeft: 12,
    paddingRight: 12,
    width: PROCESS_COLUMN_WIDTH,
  },
  cellTime: {
    alignItems: 'center',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    width: TIME_COLUMN_WIDTH,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d9d9d9',
    borderWidth: 1,
    borderTopWidth: 0,
    justifyContent: 'center',
    marginHorizontal: 16,
    marginBottom: 16,
    minHeight: 220,
  },
  nativeFallbackContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
    padding: 12,
  },
  nativeFallbackText: {
    color: '#6f6f6f',
    fontSize: 13,
    textAlign: 'center',
  },
  horizontalScrollContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    height: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
    overscrollBehavior: 'contain',
  },
  headerCell: {
    backgroundColor: '#F2F2F2',
    borderBottom: '1px solid #d0d0d0',
  },
  headerRow: {
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
    borderBottom: '1px solid #d0d0d0',
    display: 'flex',
    flexDirection: 'row',
    height: HEADER_ROW_HEIGHT,
  },
  headerText: {
    color: '#4a4a4a',
    fontWeight: 700,
  },
  row: {
    alignItems: 'center',
    borderBottom: '1px solid #e9e9e9',
    display: 'flex',
    flexDirection: 'row',
    height: ROW_HEIGHT,
  },
  rowAlternate: {
    backgroundColor: '#FFFFFF',
  },
  taskCell: {
    boxSizing: 'border-box',
    borderRight: '1px solid #e4e4e4',
    display: 'flex',
    flexDirection: 'column',
    height: ROW_HEIGHT,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  tableContainer: {
    borderColor: '#d9d9d9',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderWidth: 1,
    borderTopWidth: 0,
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    marginHorizontal: 16,
    margin: '4px 16px 24px 16px',
    minHeight: 0,
    overflow: 'hidden',
    position: 'relative',
    border: 'solid 1px #D9D9D9',
    borderRadius: '8px',
  },
  tableWidthContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
  },
  timelineHeaderPane: {
    backgroundColor: '#F2F2F2',
    borderLeft: '1px solid #e4e4e4',
    boxSizing: 'border-box',
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    minWidth: 0,
  },
  timelineTopScroll: {
    borderBottom: '1px solid #d9d9d9',
    boxSizing: 'border-box',
    height: TIMELINE_TOP_SCROLL_HEIGHT,
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  timelineTopScrollTrack: {
    height: 1,
  },
  timelineViewport: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  timelineTrack: {
    display: 'flex',
    flexDirection: 'column',
  },
  verticalScrollContainer: {
    flex: 1,
    height: '100%',
    marginRight: -18,
    minHeight: 0,
    overflowX: 'hidden',
    overflowY: 'scroll',
    overscrollBehavior: 'contain',
    paddingBottom: 8,
    paddingRight: 18,
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
  },
  verticalScrollClipContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  verticalScrollContent: {},
  leftScrollbarOverlay: {
    bottom: 8,
    left: 4,
    pointerEvents: 'auto',
    position: 'absolute',
    top: HEADER_ROW_HEIGHT + LEFT_SCROLLBAR_TOP_OFFSET,
    zIndex: 12,
  },
  leftScrollbarThumb: {
    backgroundColor: '#bdbdbd',
    borderRadius: 8,
    cursor: 'ns-resize',
    width: 6,
  },
  leftScrollbarTrack: {
    backgroundColor: '#dfdfdf',
    borderRadius: 8,
    cursor: 'pointer',
    height: '100%',
    width: 6,
  },
  zoomControlButton: {
    alignItems: 'center',
    appearance: 'none',
    backgroundColor: 'transparent',
    border: 'none',
    color: '#4f4f4f',
    cursor: 'pointer',
    display: 'flex',
    fontSize: 16,
    fontWeight: 600,
    height: 34,
    justifyContent: 'center',
    lineHeight: 1,
    minWidth: 10,
    paddingLeft: 0,
    paddingRight: 0,
  },
  zoomControlButtonDisabled: {
    opacity: 0.55,
  },
  zoomControlsContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    border: '1px solid #cfcfcf',
    borderRadius:"8px 0px 8px 0px",
    bottom: 0,
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 6,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 6,
    position: 'absolute',
    right: 0,
    zIndex: 20,
  },
  zoomLabelText: {
    color: '#4f4f4f',
    fontSize: 14,
    fontWeight: 500,
  },
  zoomPercentageButton: {
    fontSize: 15,
    fontWeight: 400,
    minWidth: 10,
  },
  zoomStepText: {
    color: '#6b6b6b',
    fontSize: 13,
    fontWeight: 500,
  },
  taskNameText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    width: '100%',
  },
  timelineCell: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    height: ROW_HEIGHT,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingVertical: TIMELINE_ROW_PADDING,
  },
} as const;
