environment: dev
region: us-east1
project_id: airportdomain-dev-daef
log_severity: DEBUG

secret_project: '831702928814'

cluster_id: projects/airportdomain-dev-daef/locations/us-east1/clusters/k8s01-us-east1
cluster_name: k8s01-us-east1
cluster_location: us-east1

#owner
repository_name: aptotatgantt

#configs

app_cpu: 100m
app_memory: 128Mi
app_ephemeral_storage: 3Gi

EXPO_PUBLIC_API_BASE_URL: https://gantt-backend-dev-854106909582.us-east1.run.app
EXPO_PUBLIC_ENV: dev
EXPO_PUBLIC_ENABLE_LOGS: true


EXPO_PUBLIC_AUTH_ENV: dev
EXPO_PUBLIC_AUTH_REDIRECT_SCHEME: compass
EXPO_PUBLIC_AUTH_REDIRECT_PATH: oauth
