/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Avatar as HangarAvatar } from '@hangar/mobile-components';
import type { AvatarProps } from './avatar.types';

/**
 * NATIVE wrapper for Avatar.
 * Pure wrapper with ref forwarding.
 */
const AvatarComponent = forwardRef<any, AvatarProps>(
  (props, ref) => {
    return <HangarAvatar ref={ref} {...props} />;
  }
);

AvatarComponent.displayName = 'Avatar';

export const Avatar = memo(AvatarComponent);
export default Avatar;
