/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Checkbox as HangarCheckBox } from '@hangar/web-components/core/Checkbox';
import type { CheckBoxProps } from './check-box.types';

/**
 * WEB wrapper for CheckBox.
 * Pure wrapper with ref forwarding.
 */
const CheckBoxComponent = forwardRef<any, CheckBoxProps>(
  (props, ref) => {
    return <HangarCheckBox ref={ref} {...props} />;
  }
);

CheckBoxComponent.displayName = 'CheckBox';

export const CheckBox = memo(CheckBoxComponent);
export default CheckBox;
