/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Checkbox as HangarCheckBox } from '@hangar/web-components/core/Checkbox';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type CheckBoxProps = ComponentProps<typeof HangarCheckBox>;
