import fs from 'fs';
import path from 'path';

import { DESIGN_SYSTEM_COMPONENTS } from './config/design-system.config';
import { AstService } from './core/ast.service';
import { TemplateService } from './core/template.service';
import { FileService } from './core/file.service';

const BASE_PATH = path.resolve('presentation/components/design-system');

const astService = new AstService();
const templateService = new TemplateService();

const AUTO_GENERATED = `/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */
`;

const toKebabCase = (name: string): string =>
  name.replace(
    /[A-Z]/g,
    (letter, index) => `${index === 0 ? '' : '-'}${letter.toLowerCase()}`,
  );

function ensureBasePath(): void {
  if (!fs.existsSync(BASE_PATH)) {
    fs.mkdirSync(BASE_PATH, { recursive: true });
  }
}

const IGNORED_FOLDERS = ['icon'];

function validateFolderIntegrity(): void {
  const existing = fs
    .readdirSync(BASE_PATH)
    .filter((file) => fs.statSync(path.join(BASE_PATH, file)).isDirectory())
    .filter((folder) => !IGNORED_FOLDERS.includes(folder));

  const expected = DESIGN_SYSTEM_COMPONENTS.map((c) => toKebabCase(c.name));

  const missing = expected.filter((f) => !existing.includes(f));
  const extra = existing.filter((f) => !expected.includes(f));

  if (missing.length) {
    throw new Error(`❌ Missing wrappers: ${missing.join(', ')}`);
  }

  if (extra.length) {
    throw new Error(`❌ Extra wrapper folders: ${extra.join(', ')}`);
  }
}

function generateBarrels(
  components: typeof DESIGN_SYSTEM_COMPONENTS,
  platform: 'web' | 'native',
): void {
  const content =
    AUTO_GENERATED +
    components
      .filter((component) =>
        platform === 'web'
          ? Boolean(component.webImportPath)
          : Boolean(component.nativeImportPath),
      )
      .map((component) => {
        const folder = toKebabCase(component.name);
        return `export { ${component.name} } from './${folder}/${folder}.${platform}';`;
      })
      .join('\n') +
    '\n';

  FileService.writeIfChanged(
    path.join(BASE_PATH, `index.${platform}.ts`),
    content,
  );
}

async function build(): Promise<void> {
  ensureBasePath();

  const globalExports: string[] = [];

  for (const component of DESIGN_SYSTEM_COMPONENTS) {
    const folder = toKebabCase(component.name);
    const componentPath = path.join(BASE_PATH, folder);

    if (!fs.existsSync(componentPath)) {
      fs.mkdirSync(componentPath, { recursive: true });
    }

    const importPath = component.webImportPath || component.nativeImportPath;

    if (!importPath) {
      throw new Error(
        `❌ ${component.name} must define at least one import path`,
      );
    }

    const typesExportName = importPath.includes('web-components')
      ? importPath.split('/').pop()
      : component.name;

    const types =
      AUTO_GENERATED +
      astService.generatePropsAlias(
        component.name,
        importPath,
        typesExportName,
      );

    FileService.writeIfChanged(
      path.join(componentPath, `${folder}.types.ts`),
      types,
    );

    if (component.webImportPath) {
      const webExportName = component.webImportPath.split('/').pop();
      const web =
        AUTO_GENERATED +
        templateService.generateComponentTemplate(
          component.name,
          component.webImportPath,
          'web',
          webExportName,
        );

      FileService.writeIfChanged(
        path.join(componentPath, `${folder}.web.tsx`),
        web,
      );
    }

    if (component.nativeImportPath) {
      const native =
        AUTO_GENERATED +
        templateService.generateComponentTemplate(
          component.name,
          component.nativeImportPath,
          'native',
        );

      FileService.writeIfChanged(
        path.join(componentPath, `${folder}.native.tsx`),
        native,
      );
    }

    const localIndex =
      AUTO_GENERATED +
      `
export { ${component.name} } from './${folder}';
export type { ${component.name}Props } from './${folder}.types';
`;

    FileService.writeIfChanged(
      path.join(componentPath, 'index.ts'),
      localIndex,
    );

    globalExports.push(`export { ${component.name} } from './${folder}';`);
  }

  const globalIndex = AUTO_GENERATED + globalExports.join('\n') + '\n';

  FileService.writeIfChanged(path.join(BASE_PATH, 'index.ts'), globalIndex);

  generateBarrels(DESIGN_SYSTEM_COMPONENTS, 'web');
  generateBarrels(DESIGN_SYSTEM_COMPONENTS, 'native');

  validateFolderIntegrity();

  console.log('✅ Design System build completed');
}

build();
