declare module '@hangar/mobile-components' {
  export const Alert: any;
  export const Avatar: any;
  export const BottomNavigation: any;
  export const Box: any;
  export const Button: any;
  export const CheckBox: any;
  export const Chip: any;
  export const Divider: any;
  export const IconButton: any;
  export const Link: any;
  export const Menu: any;
  export const MessageCard: any;
  export const Notification: any;
  export const Picker: any;
  export const Quantity: any;
  export const RadioGroup: any;
  export const Skeleton: any;
  export const Spinner: any;
  export const Switch: any;
  export const Tabs: any;
  export const Tag: any;
  export const Text: any;
  export const TextArea: any;
  export const TextField: any;
  export const TextList: any;
  export const Tile: any;
}
