/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Alert as HangarAlert } from '@hangar/web-components/core/Alert';
import type { AlertProps } from './alert.types';

/**
 * WEB wrapper for Alert.
 * Pure wrapper with ref forwarding.
 */
const AlertComponent = forwardRef<any, AlertProps>(
  (props, ref) => {
    return <HangarAlert ref={ref} {...props} />;
  }
);

AlertComponent.displayName = 'Alert';

export const Alert = memo(AlertComponent);
export default Alert;
