/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Alert as HangarAlert } from '@hangar/web-components/core/Alert';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type AlertProps = ComponentProps<typeof HangarAlert>;
