/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Tabs as HangarTabs } from '@hangar/mobile-components';
import type { TabsProps } from './tabs.types';

/**
 * NATIVE wrapper for Tabs.
 * Pure wrapper with ref forwarding.
 */
const TabsComponent = forwardRef<any, TabsProps>(
  (props, ref) => {
    return <HangarTabs ref={ref} {...props} />;
  }
);

TabsComponent.displayName = 'Tabs';

export const Tabs = memo(TabsComponent);
export default Tabs;
