/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Select as HangarSelect } from '@hangar/web-components/core/Select';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type SelectProps = ComponentProps<typeof HangarSelect>;
