/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Select as HangarSelect } from '@hangar/web-components/core/Select';
import type { SelectProps } from './select.types';

/**
 * WEB wrapper for Select.
 * Pure wrapper with ref forwarding.
 */
const SelectComponent = forwardRef<any, SelectProps>(
  (props, ref) => {
    return <HangarSelect ref={ref} {...props} />;
  }
);

SelectComponent.displayName = 'Select';

export const Select = memo(SelectComponent);
export default Select;
