export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    overflow: 'hidden' as const,
  },
  headerBar: {
    minHeight: 92,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  headerTitle: {
    color: '#303030',
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  searchBlock: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    gap: 14,
    borderBottomWidth: 1,
  },
  searchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  searchField: {
    flex: 1,
    minHeight: 58,
    borderWidth: 1.5,
    borderRadius: 12,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  refreshButton: {
    width: 58,
    height: 58,
    borderRadius: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#2c31c9',
  },
  searchInput: {
    flex: 1,
    color: '#303030',
    fontSize: 18,
    paddingVertical: 0,
  },
  orderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  orderLabel: {
    color: '#626262',
    fontSize: 16,
  },
  orderChips: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  orderChip: {
    minHeight: 48,
    minWidth: 96,
    borderRadius: 999,
    paddingHorizontal: 18,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
  },
  orderChipActive: {
    backgroundColor: '#2c31c9',
  },
  orderChipIdle: {
    backgroundColor: '#efefef',
  },
  body: {
    flex: 1,
    minHeight: 0,
  },
  listScroll: {
    flex: 1,
  },
  listScrollContent: {
    paddingBottom: 18,
    backgroundColor: '#ffffff',
  },
  sectionBlock: {
    backgroundColor: '#ffffff',
  },
  sectionHeader: {
    minHeight: 58,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sectionHeaderLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  sectionHeaderRight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  sectionCount: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: 8,
    borderRadius: 999,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  sectionFlights: {
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  emptySection: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 24,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 24,
  },
  itemPressable: {
    width: '100%',
  },
  itemCard: {
    minHeight: 84,
    flexDirection: 'row' as const,
    borderRadius: 12,
    overflow: 'hidden' as const,
    backgroundColor: '#ffffff',
  },
  itemStatusBar: {
    width: 8,
    height: '100%',
  },
  itemContent: {
    flex: 1,
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  itemLeft: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'space-evenly' as const,
  },
  itemNumberRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    flexWrap: 'wrap' as const,
  },
  itemConnectionRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  itemRight: {
    width: 146,
    alignItems: 'flex-end' as const,
    justifyContent: 'space-evenly' as const,
  },
  itemTopBadges: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  itemAircraftTag: {
    minHeight: 30,
    paddingHorizontal: 9,
    borderWidth: 2,
    borderRadius: 5,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#ffffff',
  },
  itemPriorityTag: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
} as const;
