/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { IconButton as HangarIconButton } from '@hangar/web-components/core/IconButton';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type IconButtonProps = ComponentProps<typeof HangarIconButton>;
