/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { IconButton as HangarIconButton } from '@hangar/mobile-components';
import type { IconButtonProps } from './icon-button.types';

/**
 * NATIVE wrapper for IconButton.
 * Pure wrapper with ref forwarding.
 */
const IconButtonComponent = forwardRef<any, IconButtonProps>(
  (props, ref) => {
    return <HangarIconButton ref={ref} {...props} />;
  }
);

IconButtonComponent.displayName = 'IconButton';

export const IconButton = memo(IconButtonComponent);
export default IconButton;
