/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { TextList as HangarTextList } from '@hangar/web-components/core/TextList';
import type { TextListProps } from './text-list.types';

/**
 * WEB wrapper for TextList.
 * Pure wrapper with ref forwarding.
 */
const TextListComponent = forwardRef<any, TextListProps>(
  (props, ref) => {
    return <HangarTextList ref={ref} {...props} />;
  }
);

TextListComponent.displayName = 'TextList';

export const TextList = memo(TextListComponent);
export default TextList;
