/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { TextList as HangarTextList } from '@hangar/web-components/core/TextList';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type TextListProps = ComponentProps<typeof HangarTextList>;
