/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { MessageCard as HangarMessageCard } from '@hangar/web-components/core/MessageCard';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type MessageCardProps = ComponentProps<typeof HangarMessageCard>;
