/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { MessageCard as HangarMessageCard } from '@hangar/mobile-components';
import type { MessageCardProps } from './message-card.types';

/**
 * NATIVE wrapper for MessageCard.
 * Pure wrapper with ref forwarding.
 */
const MessageCardComponent = forwardRef<any, MessageCardProps>(
  (props, ref) => {
    return <HangarMessageCard ref={ref} {...props} />;
  }
);

MessageCardComponent.displayName = 'MessageCard';

export const MessageCard = memo(MessageCardComponent);
export default MessageCard;
