/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Menu as HangarMenu } from '@hangar/mobile-components';
import type { MenuProps } from './menu.types';

/**
 * NATIVE wrapper for Menu.
 * Pure wrapper with ref forwarding.
 */
const MenuComponent = forwardRef<any, MenuProps>(
  (props, ref) => {
    return <HangarMenu ref={ref} {...props} />;
  }
);

MenuComponent.displayName = 'Menu';

export const Menu = memo(MenuComponent);
export default Menu;
