/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { RadioGroup as HangarRadioGroup } from '@hangar/mobile-components';
import type { RadioGroupProps } from './radio-group.types';

/**
 * NATIVE wrapper for RadioGroup.
 * Pure wrapper with ref forwarding.
 */
const RadioGroupComponent = forwardRef<any, RadioGroupProps>(
  (props, ref) => {
    return <HangarRadioGroup ref={ref} {...props} />;
  }
);

RadioGroupComponent.displayName = 'RadioGroup';

export const RadioGroup = memo(RadioGroupComponent);
export default RadioGroup;
