/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { RadioGroup as HangarRadioGroup } from '@hangar/web-components/core/RadioGroup';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type RadioGroupProps = ComponentProps<typeof HangarRadioGroup>;
