/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Popover as HangarPopover } from '@hangar/web-components/core/Popover';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type PopoverProps = ComponentProps<typeof HangarPopover>;
