/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Popover as HangarPopover } from '@hangar/web-components/core/Popover';
import type { PopoverProps } from './popover.types';

/**
 * WEB wrapper for Popover.
 * Pure wrapper with ref forwarding.
 */
const PopoverComponent = forwardRef<any, PopoverProps>(
  (props, ref) => {
    return <HangarPopover ref={ref} {...props} />;
  }
);

PopoverComponent.displayName = 'Popover';

export const Popover = memo(PopoverComponent);
export default Popover;
