export const styles = {
  overlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: "row",
    zIndex: 40,
  },
  drawer: {
    backgroundColor: "#ffffff",
    borderRightWidth: 1,
    borderRightColor: "#d9d9d9",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(21, 29, 47, 0.24)",
  },
  backdropPressable: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: {
    color: "#303030",
    fontSize: 28,
    fontWeight: "600",
  },
  closeButton: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d9d9d9",
  },
  closeButtonLabel: {
    fontSize: 16,
    color: "#5c5c5c",
    lineHeight: 16,
  },
  processSection: {
    gap: 8,
  },
  processTitle: {
    color: "#303030",
    fontSize: 16,
    fontWeight: "600",
  },
  timeFields: {
    flexDirection: "row",
    gap: 8,
  },
  timeField: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 4,
  },
  timeLabel: {
    color: "#878787",
    fontSize: 11,
    fontWeight: "500",
  },
  timeValue: {
    color: "#303030",
    fontSize: 16,
    fontWeight: "500",
  },
  commentsSection: {
    flex: 1,
    minHeight: 0,
    gap: 10,
  },
  commentsHeader: {
    color: "#303030",
    fontSize: 14,
    fontWeight: "600",
  },
  errorText: {
    color: "#a60f0f",
    fontSize: 12,
  },
  commentsList: {
    flex: 1,
    minHeight: 0,
  },
  commentsContent: {
    gap: 8,
    paddingBottom: 12,
  },
  commentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  authorBadge: {
    minWidth: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#ebeefe",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  authorBadgeText: {
    color: "#383dbb",
    fontSize: 11,
    fontWeight: "700",
  },
  commentBubble: {
    flex: 1,
    backgroundColor: "#f7f8fb",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  commentAuthor: {
    color: "#5c5c5c",
    fontSize: 11,
    fontWeight: "600",
  },
  commentMessage: {
    color: "#303030",
    fontSize: 13,
    lineHeight: 18,
  },
  commentTime: {
    color: "#878787",
    fontSize: 11,
    textAlign: "right",
  },
  emptyText: {
    color: "#878787",
    fontSize: 12,
    textAlign: "center",
    marginTop: 12,
  },
  composer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  composerInputWrapper: {
    flex: 1,
  },
  composerInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderRadius: 8,
    paddingHorizontal: 12,
    color: "#303030",
    backgroundColor: "#ffffff",
  },
  sendButton: {
    minWidth: 92,
    height: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  sendButtonEnabled: {
    backgroundColor: "#2f34c3",
  },
  sendButtonDisabled: {
    backgroundColor: "#b8bbdd",
  },
  sendButtonLabel: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
} as const;
