/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { TextField as HangarTextField } from '@hangar/web-components/core/TextField';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type TextFieldProps = ComponentProps<typeof HangarTextField>;
