/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { TextField as HangarTextField } from '@hangar/mobile-components';
import type { TextFieldProps } from './text-field.types';

/**
 * NATIVE wrapper for TextField.
 * Pure wrapper with ref forwarding.
 */
const TextFieldComponent = forwardRef<any, TextFieldProps>(
  (props, ref) => {
    return <HangarTextField ref={ref} {...props} />;
  }
);

TextFieldComponent.displayName = 'TextField';

export const TextField = memo(TextFieldComponent);
export default TextField;
