import { webOnly } from '@/shared/utils/platform-style';

/**
 * Estilos compartidos para FlightList (web y native).
 * Propiedades solo web aisladas con webOnly().
 */
export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    alignItems: 'stretch',
    alignSelf: 'stretch',
    padding: 0,
    borderRightWidth: 1,
    height: '100%',
    minHeight: 0,
    flexGrow: 0,
    flexShrink: 0,
    ...webOnly({ transition: 'width 200ms ease', willChange: 'width' }),
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
  },
  headerBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 24,
    paddingRight: 16,
    borderBottomWidth: 1,
    justifyContent: 'space-between',
    height: 64,
  },
  toggleButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    opacity: 1,
    transform: 'rotate(0deg)',
    ...webOnly({ cursor: 'pointer' }),
  },
  searchBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 24,
    paddingRight: 16,
    borderBottomWidth: 1,
  },
  dateSelectorBlock: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 24,
    paddingRight: 24,
    borderBottomWidth: 1,
  },
  dateNavButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    ...webOnly({ cursor: 'pointer' }),
  },
  datePickerButton: {
    flex: 1,
    flexDirection: 'row' as const,
    minWidth: 170,
    maxHeight: 48,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 12,
    backgroundColor: '#ffffff',
    ...webOnly({
      display: 'inline-flex',
      padding: '12px 12px',
      boxSizing: 'border-box',
      appearance: 'none',
      borderStyle: 'solid',
      cursor: 'pointer',
    }),
  },
  datePickerIconWrapper: {
    width: 24,
    height: 24,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  datePickerText: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '500' as const,
  },
  datePickerInput: {
    position: 'absolute' as const,
    inset: 0,
    opacity: 0,
    pointerEvents: 'none' as const,
  },
  datePickerModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.24)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 24,
  },
  datePickerModalCard: {
    width: '100%' as const,
    maxWidth: 360,
    borderWidth: 1,
    borderRadius: 16,
    paddingTop: 18,
    paddingBottom: 16,
    paddingHorizontal: 16,
    gap: 12,
  },
  datePickerModalHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
  },
  datePickerModalTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600' as const,
  },
  datePickerModalList: {
    maxHeight: 320,
  },
  datePickerModalListContent: {
    gap: 8,
  },
  datePickerModalOption: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  datePickerModalOptionText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500' as const,
  },
  datePickerModalCloseButton: {
    alignSelf: 'flex-end' as const,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  datePickerModalCloseText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '600' as const,
  },
  searchField: { width: '100%' },
  orderRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  orderChips: { display: 'flex', flexDirection: 'row', gap: 8 },
  sectionHeaderVoos: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  sectionHeaderContentVoos: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    flex: 1,
  },
  sectionHeaderLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sectionHeaderRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionList: {
    paddingTop: 16,
    paddingBottom: 16,
  },
  sectionListContainer: { width: '100%', overflow: 'hidden' },
  sectionListScroll: { width: '100%', height: '100%' },
  /** Contenedor sin scroll: dos bloques (Meus Voos / Otros Voos), cada uno con su FlightListVirtualized. */
  sectionListNoScroll: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    flexDirection: 'column' as const,
  },
  /** Cada sección: header + lista virtualizada con scroll propio. */
  sectionBlock: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    flexDirection: 'column' as const,
  },
  /** Sección que solo ocupa el espacio de su contenido (ej. Meus Voos sin flex). */
  sectionBlockAutoHeight: {
    flexGrow: 0,
    flexShrink: 0,
    width: '100%',
    flexDirection: 'column' as const,
  },
  /** Envuelve la lista para que en native (FlatList) ocupe el resto del bloque. */
  sectionListWrapper: {
    flex: 1,
    minHeight: 0,
    width: '100%',
  },
  /** Contenedor del bloque de vuelos visible para la fecha seleccionada. */
  dateGroupContainer: {
    flexDirection: 'column' as const,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 24,
    paddingRight: 16,
    gap: 12,
  },
  /** Tarjeta del ítem de vuelo: contenedor presionable (68px alto). */
  cardPressable: {
    width: '100%',
    height: 68,
    maxHeight: 68,
  },
  /** Contenedor interior de la tarjeta: fila con barra de estado + cuerpo. borderRadius/backgroundColor dinámicos. */
  itemInner: {
    flexDirection: 'row' as const,
    flex: 1,
    overflow: 'hidden' as const,
  },
  /** Barra de estado (color por estado del vuelo). width/radius izquierdos; color dinámico. */
  itemStatusBar: {
    width: 8,
    height: '100%' as const,
  },
  /** Columna izquierda: número de vuelo, destino, fila de conexión (llegada/origen). */
  itemBodyColumn: {
    flex: 1,
    flexDirection: 'column' as const,
    alignItems: 'flex-start' as const,
    paddingVertical: 12,
    paddingLeft: 8,
    justifyContent: 'space-between',
    gap: 12,
  },
  /** Fila del número de vuelo y código destino. */
  itemFlightNumberRow: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  /** Fila de conexión: icono, número llegada, origen. */
  itemConnectionRow: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    // paddingTop: 4,
  },
  /** Columna derecha: tag matrícula (PR-XDR) y ETA/STD. */
  itemRightColumn: {
    justifyContent: 'space-between' as const,
    paddingVertical: 12,
    paddingRight: 16,
    alignItems: 'flex-end' as const,
  },
  itemTopBadges: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  /** Caja del tag de matrícula de aeronave. borderColor dinámico. */
  itemAircraftTag: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 2,
    borderRadius: 4,
    width: 'auto',
  },
  itemPriorityTag: {
    fontSize: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  separator: { height: 24 },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    padding: 16,
  },
  emptyContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: 16,
  },
  sectionEmptyMessage: {
    paddingLeft: 24,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
    flex: 1,
  },
  collapsedContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    flex: 1,
    minHeight: 0,
  },
  collapsedHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    height: 64,
    width: '100%',
  },
  collapsedIcons: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 16,
    paddingTop: 16,
    paddingBottom: 16,
    flex: 1,
  },
  collapsedIconBlock: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    gap: 6,
  },
  collapsedIconButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerSectionVoosList: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 24,
    paddingRight: 12,
    flex: 1,
  },
} as const;
