/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Tag as HangarTag } from '@hangar/mobile-components';
import type { TagProps } from './tag.types';

/**
 * NATIVE wrapper for Tag.
 * Pure wrapper with ref forwarding.
 */
const TagComponent = forwardRef<any, TagProps>(
  (props, ref) => {
    return <HangarTag ref={ref} {...props} />;
  }
);

TagComponent.displayName = 'Tag';

export const Tag = memo(TagComponent);
export default Tag;
