/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Tag as HangarTag } from '@hangar/web-components/core/Tag';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type TagProps = ComponentProps<typeof HangarTag>;
