/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Tile as HangarTile } from '@hangar/web-components/core/Tile';
import type { TileProps } from './tile.types';

/**
 * WEB wrapper for Tile.
 * Pure wrapper with ref forwarding.
 */
const TileComponent = forwardRef<any, TileProps>(
  (props, ref) => {
    return <HangarTile ref={ref} {...props} />;
  }
);

TileComponent.displayName = 'Tile';

export const Tile = memo(TileComponent);
export default Tile;
