/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Box as HangarBox } from '@hangar/web-components/core/Box';
import type { BoxProps } from './box.types';

/**
 * WEB wrapper for Box.
 * Pure wrapper with ref forwarding.
 */
const BoxComponent = forwardRef<any, BoxProps>(
  (props, ref) => {
    return <HangarBox ref={ref} {...props} />;
  }
);

BoxComponent.displayName = 'Box';

export const Box = memo(BoxComponent);
export default Box;
