/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Box as HangarBox } from '@hangar/web-components/core/Box';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type BoxProps = ComponentProps<typeof HangarBox>;
