/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Quantity as HangarQuantity } from '@hangar/mobile-components';
import type { QuantityProps } from './quantity.types';

/**
 * NATIVE wrapper for Quantity.
 * Pure wrapper with ref forwarding.
 */
const QuantityComponent = forwardRef<any, QuantityProps>(
  (props, ref) => {
    return <HangarQuantity ref={ref} {...props} />;
  }
);

QuantityComponent.displayName = 'Quantity';

export const Quantity = memo(QuantityComponent);
export default Quantity;
