/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Quantity as HangarQuantity } from '@hangar/web-components/core/Quantity';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type QuantityProps = ComponentProps<typeof HangarQuantity>;
