/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { TextArea as HangarTextArea } from '@hangar/mobile-components';
import type { TextAreaProps } from './text-area.types';

/**
 * NATIVE wrapper for TextArea.
 * Pure wrapper with ref forwarding.
 */
const TextAreaComponent = forwardRef<any, TextAreaProps>(
  (props, ref) => {
    return <HangarTextArea ref={ref} {...props} />;
  }
);

TextAreaComponent.displayName = 'TextArea';

export const TextArea = memo(TextAreaComponent);
export default TextArea;
