/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Spinner as HangarSpinner } from '@hangar/web-components/core/Spinner';
import type { SpinnerProps } from './spinner.types';

/**
 * WEB wrapper for Spinner.
 * Pure wrapper with ref forwarding.
 */
const SpinnerComponent = forwardRef<any, SpinnerProps>(
  (props, ref) => {
    return <HangarSpinner ref={ref} {...props} />;
  }
);

SpinnerComponent.displayName = 'Spinner';

export const Spinner = memo(SpinnerComponent);
export default Spinner;
