/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Spinner as HangarSpinner } from '@hangar/web-components/core/Spinner';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type SpinnerProps = ComponentProps<typeof HangarSpinner>;
