/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Picker as HangarPicker } from '@hangar/mobile-components';
import type { PickerProps } from './picker.types';

/**
 * NATIVE wrapper for Picker.
 * Pure wrapper with ref forwarding.
 */
const PickerComponent = forwardRef<any, PickerProps>(
  (props, ref) => {
    return <HangarPicker ref={ref} {...props} />;
  }
);

PickerComponent.displayName = 'Picker';

export const Picker = memo(PickerComponent);
export default Picker;
