/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Picker as HangarPicker } from '@hangar/mobile-components';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type PickerProps = ComponentProps<typeof HangarPicker>;
