/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Chip as HangarChip } from '@hangar/web-components/core/Chip';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type ChipProps = ComponentProps<typeof HangarChip>;
