/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Chip as HangarChip } from '@hangar/mobile-components';
import type { ChipProps } from './chip.types';

/**
 * NATIVE wrapper for Chip.
 * Pure wrapper with ref forwarding.
 */
const ChipComponent = forwardRef<any, ChipProps>(
  (props, ref) => {
    return <HangarChip ref={ref} {...props} />;
  }
);

ChipComponent.displayName = 'Chip';

export const Chip = memo(ChipComponent);
export default Chip;
