/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { BottomNavigation as HangarBottomNavigation } from '@hangar/mobile-components';
import type { BottomNavigationProps } from './bottom-navigation.types';

/**
 * NATIVE wrapper for BottomNavigation.
 * Pure wrapper with ref forwarding.
 */
const BottomNavigationComponent = forwardRef<any, BottomNavigationProps>(
  (props, ref) => {
    return <HangarBottomNavigation ref={ref} {...props} />;
  }
);

BottomNavigationComponent.displayName = 'BottomNavigation';

export const BottomNavigation = memo(BottomNavigationComponent);
export default BottomNavigation;
