/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

export { BottomNavigation } from './bottom-navigation';
export type { BottomNavigationProps } from './bottom-navigation.types';
