/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Divider as HangarDivider } from '@hangar/web-components/core/Divider';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type DividerProps = ComponentProps<typeof HangarDivider>;
