/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Divider as HangarDivider } from '@hangar/web-components/core/Divider';
import type { DividerProps } from './divider.types';

/**
 * WEB wrapper for Divider.
 * Pure wrapper with ref forwarding.
 */
const DividerComponent = forwardRef<any, DividerProps>(
  (props, ref) => {
    return <HangarDivider ref={ref} {...props} />;
  }
);

DividerComponent.displayName = 'Divider';

export const Divider = memo(DividerComponent);
export default Divider;
