/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Switch as HangarSwitch } from '@hangar/mobile-components';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type SwitchProps = ComponentProps<typeof HangarSwitch>;
