/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Switch as HangarSwitch } from '@hangar/mobile-components';
import type { SwitchProps } from './switch.types';

/**
 * NATIVE wrapper for Switch.
 * Pure wrapper with ref forwarding.
 */
const SwitchComponent = forwardRef<any, SwitchProps>(
  (props, ref) => {
    return <HangarSwitch ref={ref} {...props} />;
  }
);

SwitchComponent.displayName = 'Switch';

export const Switch = memo(SwitchComponent);
export default Switch;
