/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Link as HangarLink } from '@hangar/web-components/core/Link';
import type { LinkProps } from './link.types';

/**
 * WEB wrapper for Link.
 * Pure wrapper with ref forwarding.
 */
const LinkComponent = forwardRef<any, LinkProps>(
  (props, ref) => {
    return <HangarLink ref={ref} {...props} />;
  }
);

LinkComponent.displayName = 'Link';

export const Link = memo(LinkComponent);
export default Link;
