/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Link as HangarLink } from '@hangar/web-components/core/Link';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type LinkProps = ComponentProps<typeof HangarLink>;
