/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Modal as HangarModal } from '@hangar/web-components/core/Modal';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type ModalProps = ComponentProps<typeof HangarModal>;
