/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Modal as HangarModal } from '@hangar/web-components/core/Modal';
import type { ModalProps } from './modal.types';

/**
 * WEB wrapper for Modal.
 * Pure wrapper with ref forwarding.
 */
const ModalComponent = forwardRef<any, ModalProps>(
  (props, ref) => {
    return <HangarModal ref={ref} {...props} />;
  }
);

ModalComponent.displayName = 'Modal';

export const Modal = memo(ModalComponent);
export default Modal;
