/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Notification as HangarNotification } from '@hangar/mobile-components';
import type { NotificationProps } from './notification.types';

/**
 * NATIVE wrapper for Notification.
 * Pure wrapper with ref forwarding.
 */
const NotificationComponent = forwardRef<any, NotificationProps>(
  (props, ref) => {
    return <HangarNotification ref={ref} {...props} />;
  }
);

NotificationComponent.displayName = 'Notification';

export const Notification = memo(NotificationComponent);
export default Notification;
