/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Button as HangarButton } from '@hangar/web-components/core/Button';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type ButtonProps = ComponentProps<typeof HangarButton>;
