/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Button as HangarButton } from '@hangar/web-components/core/Button';
import type { ButtonProps } from './button.types';

/**
 * WEB wrapper for Button.
 * Pure wrapper with ref forwarding.
 */
const ButtonComponent = forwardRef<any, ButtonProps>(
  (props, ref) => {
    return <HangarButton ref={ref} {...props} />;
  }
);

ButtonComponent.displayName = 'Button';

export const Button = memo(ButtonComponent);
export default Button;
