export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#F3F2F6',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
    gap: 14,
  },
  legToggleRow: {
    flexDirection: 'row' as const,
    gap: 10,
  },
  legToggleButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 8,
    paddingHorizontal: 16,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
  },
  legToggleButtonActive: {
    backgroundColor: '#2c31c9',
  },
  legToggleButtonInactive: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#2c31c9',
  },
  legToggleText: {
    color: '#2c31c9',
    fontSize: 16,
    fontWeight: 900,
    fontStyle: 'bold',
  },
  legToggleTextActive: {
    color: '#ffffff',
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 24,
  },
  stateCard: {
    width: '100%',
    maxWidth: 420,
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  stateText: {
    color: '#303030',
    textAlign: 'center' as const,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  detailCard: {
    paddingTop: 12,
  },
  cardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
  },
  flightHeaderTitleRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
  },
  sectionTitle: {
    color: '#070B64',
    fontSize: 18,
    fontWeight: 700,
    fontStyle: 'bold',
  },
  stationTitle: {
    color: '#070B64',
    fontSize: 15,
    fontWeight: 500,
    fontStyle: 'light',
  },
  gateLabelBlock: {
    alignItems: 'flex-end' as const,
    justifyContent: 'flex-end' as const,
    gap: 0,
  },
  gateLabel: {
    color: '#404040',
    letterSpacing: 0,
    paddingBottom: 6,
  },
  gateValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'right' as const,
    fontSyle: 'bold',
    fontWeight: 700,
  },
  flightSummaryRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    justifyContent: 'space-between' as const,
    gap: 10,
  },
  flightNumberRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row' as const,
    gap: 8,
  },
  flightSummaryRight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    flexShrink: 0,
    gap: 10,
  },
  flightNumberBlock: {
    gap: 2,
  },
  flightNumber: {
    color: '#303030',
    fontSize: 28,
    lineHeight: 30,
    fontStyle: 'bold',
    fontWeight: 700,
  },
  titleVoos: {
    color: '#303030',
    fontSize: 20,
    lineHeight: 20,
    fontStyle: 'bold',
    fontWeight: 700,
  },
  flightNumberUnderline: {
    width: 64,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#8d45ff',
  },
  dateBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#E7E8FD',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  dateBadgeText: {
    color: '#070B64',
    fontStyle: 'bold',
    fontWeight: 700,
  },
  badgeRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    justifyContent: 'flex-end' as const,
    flexShrink: 0,
  },
  softBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#FDF0E7',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  neutralBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#E7E8FD',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  badgeText: {
    color: '#070B64',
    fontStyle: 'bold',
    fontWeight: 700,
    fontSize: 14,
  },
  statsRow: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    gap: 12,
    paddingTop: 24,
  },
  statsLeft: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    justifyContent: 'flex-start' as const,
    flexGrow: 0,
    flexShrink: 1,
    gap: 14,
  },
  statsRight: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    flexShrink: 0,
    gap: 10,
    marginLeft: 'auto' as const,
  },
  statColumn: {
    minWidth: 58,
    gap: 4,
  },
  actionTimeColumn: {
    width: 104,
    alignItems: 'flex-end' as const,
    gap: 4,
  },
  statDivider: {
    width: 1,
    backgroundColor: '#dddddd',
  },
  statLabel: {
    color: '#404040',
    fontSize: 14,
    lineHeight: 13,
  },
  statValue: {
    color: '#303030',
    fontSize: 22,
    lineHeight: 24,
    fontStyle: 'bold',
    fontWeight: 700,
  },
  statLabelRight: {
    textAlign: 'right' as const,
  },
  statValueRight: {
    textAlign: 'right' as const,
  },
  sectionHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 10,
    paddingTop: 12,
  },
  sectionHeaderRowPax: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 10,
    paddingBottom: 12,
  },
  sectionHeaderTitle: {
    color: '#303030',
    fontSize: 16,
  },
  sectionLink: {
    color: '#2c31c9',
    textDecorationLine: 'underline' as const,
    fontSize: 13,
  },
  paxMetricsRow: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
  },
  paxMetric: {
    flex: 1,
    gap: 6,
  },
  paxDivider: {
    width: 1,
    marginHorizontal: 10,
    backgroundColor: '#dddddd',
  },
  paxLabel: {
    color: '#404040',
    fontSize: 11,
  },
  paxValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
  },
  pnaeGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    columnGap: 14,
    rowGap: 14,
  },
  pnaePill: {
    width: '31%',
    minWidth: 92,
    minHeight: 68,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#d2d2d2',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
  },
  pnaeValue: {
    color: '#5a5a5a',
    fontSize: 24,
    lineHeight: 26,
  },
  processesSection: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#d9d9d9',
    gap: 12,
  },
  processCards: {
    gap: 10,
  },
  boardingProcessesSection: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#d9d9d9',
    gap: 12,
  },
  processCard: {
    gap: 0,
  },
  processCardExpanded: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: '#d7d7d7',
  },
  processHeaderRow: {
    paddingHorizontal: 2,
    paddingBottom: 0,
    zIndex: 1,
  },
  processHeaderCapsule: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    alignSelf: 'flex-start' as const,
    overflow: 'hidden' as const,
    maxWidth: '100%',
  },
  processExpandedHeader: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
  },
  processExpandedTitle: {
    flex: 1,
    color: '#303030',
    fontWeight: 700,
    fontStyle: 'bold',
  },
  processEditButton: {
    width: 36,
    height: 36,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  processTitleChip: {
    backgroundColor: '#2c31c9',
    paddingHorizontal: 18,
    paddingVertical: 4,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 0,
    alignSelf: 'flex-end' as const,
  },
  processTitleChipText: {
    color: '#ffffff',
  },
  processStatusChip: {
    paddingHorizontal: 18,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 0,
    position: 'relative' as const,
    paddingLeft: 32,
    left: -6,
    zIndex: -1,
  },
  processStatusChipText: {
    color: '#3b3128',
  },
  processStatusCompleted: {
    backgroundColor: '#c9eef1',
  },
  processStatusInProgress: {
    backgroundColor: '#f3e7da',
  },
  processStatusPending: {
    backgroundColor: '#ececff',
  },
  processExpandedGrid: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
  },
  processExpandedMetric: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
  },
  processExpandedMetricScheduled: {
    flex: 1.25,
  },
  processExpandedMetricCompact: {
    flex: 0.8,
  },
  processExpandedDivider: {
    width: 1,
    backgroundColor: '#dddddd',
    marginHorizontal: 10,
  },
  processMetricsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginTop: -6,
    paddingTop: 18,
    paddingBottom: 12,
    paddingHorizontal: 2,
  },
  processMetricsRow: {
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 10,
  },
  processMetric: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
  },
  processMetricSingle: {
    flex: 0,
    alignSelf: 'center' as const,
    minWidth: 180,
  },
  processMetricDivider: {
    width: 1,
    backgroundColor: '#dddddd',
    marginHorizontal: 10,
  },
  processMetricValue: {
    color: '#303030',
    fontSize: 22,
    lineHeight: 24,
  },
  processMetricLabel: {
    color: '#646464',
    textAlign: 'center' as const,
    fontSize: 11,
  },
  processExpandedMetricValue: {
    color: '#303030',
    textAlign: 'center' as const,
    fontWeight: 700,
    fontStyle: 'bold',
    fontSize: 20,
    lineHeight: 24
  },
  processExpandedMetricLabel: {
    color: '#5C5C5C',
    textAlign: 'center' as const,
    fontSize: 12,
  },
  processExpandedFooter: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 10,
  },
  processExpandedDuration: {
    width: 100,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
  },
  processExpandedAction: {
    minWidth: 190,
    minHeight: 56,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 14,
  },
  processExpandedActionCompleted: {
    backgroundColor: '#c9eef1',
  },
  processExpandedActionInProgress: {
    backgroundColor: '#cc103d',
  },
  processExpandedActionPending: {
    backgroundColor: '#2c31c9',
  },
  processEmptyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  taskEditModalOverlay: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 18,
  },
  taskEditModalBackdrop: {
    position: 'absolute' as const,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(21, 29, 47, 0.38)',
  },
  taskEditModalCard: {
    width: '100%',
    maxWidth: 680,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 18,
  },
  taskEditModalHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 14,
  },
  taskEditModalTitle: {
    color: '#0a0e80',
    fontSize: 24,
    lineHeight: 30,
  },
  taskEditModalCloseButton: {
    width: 40,
    height: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  taskEditModalTimeRow: {
    flexDirection: 'row' as const,
    gap: 12,
    marginBottom: 14,
  },
  taskEditModalField: {
    flex: 1,
    gap: 8,
  },
  taskEditModalFieldLabel: {
    color: '#4a4a4a',
    fontSize: 16,
    lineHeight: 20,
  },
  taskEditModalInput: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
  },
  taskEditModalCommentInput: {
    minHeight: 148,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
    marginBottom: 12,
  },
  taskEditModalErrorText: {
    color: '#a60f0f',
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 10,
  },
  taskEditModalDivider: {
    height: 1,
    backgroundColor: '#d9d9d9',
    marginBottom: 16,
  },
  taskEditModalRestartButton: {
    minHeight: 58,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 20,
    backgroundColor: '#c4073f',
    marginBottom: 14,
  },
  taskEditModalRestartButtonText: {
    color: '#ffffff',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center' as const,
  },
  taskEditModalFooter: {
    flexDirection: 'row' as const,
    gap: 12,
  },
  taskEditModalCancelButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#c4073f',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
  },
  taskEditModalCancelButtonText: {
    color: '#c4073f',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center' as const,
  },
  taskEditModalSubmitButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 10,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#2c31c9',
    paddingHorizontal: 18,
  },
  taskEditModalSubmitButtonDisabled: {
    opacity: 0.55,
  },
  taskEditModalSubmitButtonText: {
    color: '#ffffff',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center' as const,
  },
} as const;
