import type { CSSProperties } from 'react';

// Typing the styles object as a Record of CSSProperties so all values
// are validated against the correct CSS type unions (FlexDirection, etc.)
export const styles: Record<string, CSSProperties> = {
  panelContainer: {
    display: 'flex',
    flexDirection: 'row',
    flex: 1,
    minHeight: 0,
    width: '100%',
    overflow: 'hidden',
  },
  mainContent: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  wrapperSupScroll: {
    flexShrink: 0,
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 0,
  },
  wrapperSup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'stretch',
    border: 'solid 1px #D9D9D9',
    borderRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    backgroundColor: '#ffffff',
    boxSizing: 'border-box',
  },
  wrapperSupCompact: {
    flexDirection: 'column',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    padding: '10px 12px',
    flex: 1,
    minWidth: 0,
    borderLeft: '4px solid #0D12AB',
    borderRight: '1px solid #D9D9D9',
    boxSizing: 'border-box',
    gap: 8,
  },
  columnR: {
    display: 'flex',
    flexDirection: 'column',
    padding: '10px 12px',
    flex: 1,
    minWidth: 0,
    borderLeft: '4px solid #0D12AB',
    borderRight: '1px solid #D9D9D9',
    boxSizing: 'border-box',
    gap: 8,
  },
  columnCompact: {
    flexShrink: 0,
    flexGrow: 0,
    flexBasis: 'auto',
    alignSelf: 'stretch',
    borderRight: '0px',
    borderBottomWidth: 1,
    borderBottomColor: '#D9D9D9',
    borderBottomStyle: 'solid',
  },
  headerInfo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  topInfoLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
    flexWrap: 'nowrap',
    minWidth: 0,
  },
  topInfoRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  bottomInfo: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  bottomInfoLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    flexShrink: 1,
    minWidth: 0,
  },
  bottomInfoRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  tagBox: {
    display: 'flex',
    alignItems: 'center',
  },
  pushInBox: {
    display: 'flex',
    flexDirection: 'column',
    textAlignLast: 'right',
    gap: 2,
  },
  verticalDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#d9d9d9',
  },
  midBox: {
    padding: '10px 16px',
    backgroundColor: '#F2F2F2',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    flex: '0 0 110px',
    minWidth: 110,
    borderRight: '1px solid #D9D9D9',
    boxSizing: 'border-box',
  },
  midBoxCompact: {
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 'auto',
    flexDirection: 'row',
    gap: 16,
    alignSelf: 'stretch',
    borderRight: '0px',
    borderBottomWidth: 1,
    borderBottomColor: '#D9D9D9',
    borderBottomStyle: 'solid',
    padding: '8px 12px',
    minWidth: 0,
  },
  estimatedTime: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 2,
    padding: '10px 16px',
    flex: '0 0 170px',
    minWidth: 0,
    boxSizing: 'border-box',
    borderLeft: '1px solid #D9D9D9',
    flexShrink: 0,
  },
  estimatedTimeCompact: {
    flex: '0 0 170px',
  },
  subBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F2F2F2',
    borderLeft: '1px solid #D9D9D9',
    borderRight: '1px solid #D9D9D9',
    borderBottom: '1px solid #D9D9D9',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    padding: '6px 12px',
    gap: 8,
    boxSizing: 'border-box',
    flexShrink: 0,
  },
  subBarLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  subBarCenter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  subBarRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'flex-end',
    minWidth: 0,
  },
  subBarDivider: {
    width: 1,
    height: 12,
    backgroundColor: '#C0C0C0',
    flexShrink: 0,
  },
  routeTypeBadge: {
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    padding: '2px 8px',
    border: '1px solid #C0C0C0',
  },
  tempoPlanBadge: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    padding: '2px 8px',
    border: '1px solid #C0C0C0',
  },
  infoItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  loadingWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    flex: 1,
  },
  loadingContent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eventsPanel: {
    display: 'flex',
    flexDirection: 'column',
    width: 332,
    minWidth: 332,
    maxWidth: 332,
    flexShrink: 0,
    minHeight: 0,
    borderLeft: '1px solid #D9D9D9',
    backgroundColor: '#ffffff',
    boxSizing: 'border-box',
  },
  eventsPanelCollapsed: {
    display: 'flex',
    flexDirection: 'column',
    width: 73,
    minWidth: 73,
    maxWidth: 73,
    alignItems: 'stretch',
    borderLeft: '1px solid #D9D9D9',
    backgroundColor: '#ffffff',
    boxSizing: 'border-box',
  },
  eventsPanelCollapsedHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 18,
    paddingBottom: 18,
    borderBottom: '1px solid #D9D9D9',
  },
  eventsPanelCollapsedActions: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 18,
    paddingTop: 28,
  },
  eventsPanelCollapsedAction: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
  },
  eventsPanelCollapsedIconButton: {
    display: 'flex',
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventsPanelCollapsedIconButtonGhost: {
    display: 'flex',
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  eventsPanelCollapsedCount: {
    display: 'flex',
    minWidth: 48,
    minHeight: 32,
    borderRadius: '999px',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4px 12px',
    boxSizing: 'border-box',
  },
  eventsPanelHeader: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: '18px 20px',
    borderBottom: '1px solid #D9D9D9',
    boxSizing: 'border-box',
  },
  eventsPanelToggle: {
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventsPanelBody: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    boxSizing: 'border-box',
  },
  eventsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 16,
    paddingRight: 16,
  },
  eventItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eventMeta: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eventTime: {
    minWidth: 40,
  },
  eventDescription: {
    lineHeight: 1.5,
  },
  eventsEmptyState: {
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
  },
  tabsBar: {
    display: 'flex',
    flexDirection: 'row',
    borderBottom: '1px solid #D9D9D9',
    paddingLeft: 16,
    paddingRight: 16,
    gap: 0,
  },
  tabItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 12,
    paddingBottom: 13,
    paddingLeft: 8,
    paddingRight: 8,
    position: 'relative',
    cursor: 'pointer',
    flex: 1,
  },
  tabActiveIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    borderRadius: 2,
  },
  eventBadge: {
    borderRadius: 6,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 7,
    paddingRight: 7,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Applied to newly added activity rows via CSS animation
  eventItemNew: {
    animation: 'slideInFromBottom 0.32s cubic-bezier(0.22, 1, 0.36, 1) both',
  },
};
