/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import React, { memo, forwardRef } from 'react';
import { Skeleton as HangarSkeleton } from '@hangar/mobile-components';
import type { SkeletonProps } from './skeleton.types';

/**
 * NATIVE wrapper for Skeleton.
 * Pure wrapper with ref forwarding.
 */
const SkeletonComponent = forwardRef<any, SkeletonProps>(
  (props, ref) => {
    return <HangarSkeleton ref={ref} {...props} />;
  }
);

SkeletonComponent.displayName = 'Skeleton';

export const Skeleton = memo(SkeletonComponent);
export default Skeleton;
