/**
 * ⚠️ AUTO-GENERATED FILE.
 * Do not edit manually.
 * Generated by ds:build.
 */

import type { ComponentProps } from 'react';
import { Skeleton as HangarSkeleton } from '@hangar/web-components/core/Skeleton';

/**
 * Auto-generated from Hangar source.
 * Do not edit manually.
 */
export type SkeletonProps = ComponentProps<typeof HangarSkeleton>;
