export const styles = {
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F3F2F6',
  },
  sidebar: {
    width: 664,
    backgroundColor: '#ffffff',
    borderRightWidth: 1,
    borderRightColor: '#d9d9d9',
  },
  sidebarScrollContent: {
    paddingBottom: 16,
  },
  sidebarTop: {
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  backButton: {
    minWidth: 112,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: '#2c31c9',
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
  },
  backButtonText: {
    fontSize: 15,
    lineHeight: 19,
  },
  headerMetrics: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    gap: 12,
    minWidth: 0,
  },
  headerMetric: {
    minWidth: 84,
    maxWidth: 110,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 1,
  },
  headerMetricLabel: {
    marginBottom: 5,
    color: '#4a4a4a',
    fontSize: 12,
    lineHeight: 15,
    textAlign: 'center',
  },
  headerMetricValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'center',
    width: '100%',
    whiteSpace: 'nowrap',
  },
  flightBlock: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  flightBlockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
    gap: 12,
  },
  flightHeaderMain: {
    flex: 1,
    minWidth: 0,
  },
  flightHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    flexShrink: 0,
    marginLeft: 'auto',
  },
  flightHeaderBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    flexShrink: 0,
    marginTop: 30,
  },
  flightTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  flightTitle: {
    color: '#0a0e80',
    fontSize: 18,
    lineHeight: 22,
  },
  flightStation: {
    color: '#0a0e80',
    fontSize: 14,
    lineHeight: 18,
  },
  flightNumberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  flightNumber: {
    color: '#303030',
    fontSize: 32,
    lineHeight: 36,
  },
  badgeText: {
    color: '#121970',
    fontSize: 13,
    lineHeight: 18,
  },
  dateBadge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#d9dcf6',
  },
  softBadge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#efe8e2',
  },
  neutralBadge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#d9dcf6',
  },
  boxColumn: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  boxLabel: {
    color: '#4a4a4a',
    fontSize: 12,
    marginBottom: 6,
  },
  boxValue: {
    color: '#303030',
    fontSize: 36,
    lineHeight: 40,
  },
  flightStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flightStatsLeft: {
    flexDirection: 'row',
    gap: 20,
  },
  statColumn: {
    minWidth: 70,
  },
  statLabel: {
    color: '#4a4a4a',
    fontSize: 13,
    lineHeight: 16,
    marginBottom: 6,
  },
  statValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
  },
  statsDivider: {
    width: 1,
    backgroundColor: '#d9d9d9',
    alignSelf: 'stretch',
    marginHorizontal: 16,
  },
  statsRight: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  statusBadge: {
    alignSelf: 'center',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#d0d0d0',
  },
  statusBadgeText: {
    color: '#303030',
    fontSize: 16,
    lineHeight: 20,
  },
  actionColumn: {
    minWidth: 102,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  tatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    backgroundColor: '#f7f7f7',
  },
  tatLabel: {
    color: '#303030',
    fontSize: 14,
  },
  tatValue: {
    color: '#303030',
    fontSize: 28,
  },
  cargoSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoTitle: {
    color: '#303030',
    fontSize: 16,
  },
  cargoMainRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoMainCard: {
    flex: 1,
    padding: 16,
  },
  cargoMainCardBorder: {
    borderRightWidth: 1,
    borderRightColor: '#d9d9d9',
  },
  cargoCardLabel: {
    color: '#303030',
    fontSize: 12,
    marginBottom: 12,
  },
  cargoValuePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#efefef',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cargoValueText: {
    color: '#303030',
    fontSize: 22,
  },
  cargoSpecialRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  cargoSpecialItem: {
    width: '47%',
  },
  cargoSpecialLabel: {
    color: '#4a4a4a',
    fontSize: 11,
    marginBottom: 8,
  },
  cargoSpecialValue: {
    alignSelf: 'flex-start',
    backgroundColor: '#efefef',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cargoSpecialValueText: {
    color: '#303030',
    fontSize: 18,
  },
  footerActions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  footerButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 56,
    borderRadius: 8,
    borderWidth: 2,
  },
  footerButtonSecondary: {
    borderColor: '#2c31c9',
    backgroundColor: '#ffffff',
  },
  footerButtonPrimary: {
    borderColor: '#2c31c9',
    backgroundColor: '#2c31c9',
  },
  mainPanel: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 16,
  },
  taskControlsSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: -20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 18,
    marginBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  toolbar: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
    marginBottom: 18,
  },
  searchField: {
    flex: 1,
    minHeight: 72,
    borderWidth: 1,
    borderColor: '#bdbdbd',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 22,
    gap: 14,
  },
  searchInput: {
    flex: 1,
    fontSize: 22,
    lineHeight: 26,
    color: '#303030',
    paddingVertical: 0,
  },
  toolbarButton: {
    minWidth: 186,
    minHeight: 72,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    backgroundColor: '#2c31c9',
  },
  reloadButton: {
    width: 72,
    minHeight: 72,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2c31c9',
    backgroundColor: '#ffffff',
  },
  categoryRow: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 18,
  },
  categoryButton: {
    flex: 1,
    minHeight: 54,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ececec',
    paddingHorizontal: 20,
  },
  categoryButtonActive: {
    backgroundColor: '#2c31c9',
  },
  toolbarButtonText: {
    fontSize: 26,
    lineHeight: 30,
  },
  categoryButtonText: {
    fontSize: 28,
    lineHeight: 32,
  },
  taskScroll: {
    flex: 1,
  },
  taskListContent: {
    gap: 22,
    paddingTop: 8,
    paddingBottom: 24,
  },
  taskCard: {
    borderWidth: 1,
    borderColor: '#d2d2d2',
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 26,
  },
  taskCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 22,
  },
  taskTitle: {
    flex: 1,
    color: '#303030',
    fontSize: 36,
    lineHeight: 42,
    marginRight: 20,
  },
  taskEditButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskMetricsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  taskMetric: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  taskMetricWide: {
    flex: 0.88,
    minWidth: 92,
    paddingHorizontal: 10,
  },
  taskMetricDivider: {
    width: 1,
    backgroundColor: '#d9d9d9',
    marginVertical: 4,
  },
  taskMetricValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 36,
    marginBottom: 8,
  },
  taskMetricValueWide: {
    width: '100%',
    textAlign: 'center',
  },
  taskMetricLabel: {
    color: '#4a4a4a',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
  },
  taskMetricLabelSingleLine: {
    width: '100%',
    fontSize: 13,
    lineHeight: 16,
  },
  taskActionWrap: {
    width: 246,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 18,
  },
  taskAction: {
    minWidth: 220,
    minHeight: 64,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  taskActionCompleted: {
    backgroundColor: '#d7f0ef',
  },
  taskActionInProgress: {
    backgroundColor: '#c4073f',
  },
  taskActionPending: {
    backgroundColor: '#2c31c9',
  },
  taskActionText: {
    fontSize: 18,
    lineHeight: 24,
    textAlign: 'center',
  },
  taskEditModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  taskEditModalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(21, 29, 47, 0.38)',
  },
  taskEditModalCard: {
    width: '72%',
    maxWidth: 1160,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 34,
    paddingTop: 30,
    paddingBottom: 28,
  },
  taskEditModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  taskEditModalTitle: {
    color: '#0a0e80',
    fontSize: 34,
    lineHeight: 40,
  },
  taskEditModalCloseButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskEditModalTimeRow: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 18,
  },
  taskEditModalField: {
    flex: 1,
    gap: 8,
  },
  taskEditModalFieldLabel: {
    color: '#4a4a4a',
    fontSize: 18,
    lineHeight: 24,
  },
  taskEditModalInput: {
    minHeight: 72,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
  },
  taskEditModalCommentInput: {
    minHeight: 168,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
    marginBottom: 12,
  },
  taskEditModalErrorText: {
    color: '#a60f0f',
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 10,
  },
  taskEditModalDivider: {
    height: 1,
    backgroundColor: '#d9d9d9',
    marginBottom: 18,
  },
  taskEditModalRestartButton: {
    minHeight: 72,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#c4073f',
    marginBottom: 16,
  },
  taskEditModalRestartButtonText: {
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
  },
  taskEditModalFooter: {
    flexDirection: 'row',
    gap: 18,
  },
  taskEditModalCancelButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#c4073f',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
  },
  taskEditModalCancelButtonText: {
    color: '#c4073f',
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
  },
  taskEditModalSubmitButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2c31c9',
    paddingHorizontal: 24,
  },
  taskEditModalSubmitButtonDisabled: {
    opacity: 0.55,
  },
  taskEditModalSubmitButtonText: {
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
  },
  detailMessage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailMessageCard: {
    padding: 24,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9d9d9',
  },
  detailMessageText: {
    fontSize: 16,
    lineHeight: 22,
  },
} as const;
