export const styles = {
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f2f2f2',
  },
  reloadingOverlay: {
    position: 'absolute' as const,
    inset: 0,
    zIndex: 100,
    backgroundColor: 'rgba(242,242,242,0.88)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 16,
  },
  reloadingText: {
    color: '#2c31c9',
    fontWeight: '700' as const,
    fontSize: 18,
  },
  sidebar: {
    width: 420,
    backgroundColor: '#ffffff',
    borderRightWidth: 1,
    borderRightColor: '#d9d9d9',
  },
  sidebarScrollContent: {
    paddingBottom: 16,
  },
  sidebarTop: {
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: '#2c31c9',
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
  },
  backButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  headerMetrics: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
    minWidth: 0,
    paddingLeft: 6,
  },
  headerMetric: {
    minWidth: 76,
    maxWidth: 112,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 1,
  },
  headerMetricLabel: {
    marginBottom: 6,
    color: '#4a4a4a',
    fontSize: 18,
    lineHeight: 18,
    textAlign: 'left',
  },
  headerMetricValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'center',
    width: '100%',
  },
  flightLegsCard: {
    marginTop: 16,
    backgroundColor: '#ffffff',
  },
  flightLegDivider: {
    height: 1,
    alignSelf: 'stretch',
    backgroundColor: '#d9d9d9',
  },
  flightBlock: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  flightCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  flightHeaderTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionTitle: {
    color: '#070B64',
    fontSize: 18,
    fontWeight: 700,
    fontStyle: 'bold',
  },
  stationTitle: {
    color: '#070B64',
    fontSize: 15,
    fontWeight: 500,
  },
  gateLabelBlock: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  gateLabel: {
    color: '#404040',
    paddingBottom: 6,
  },
  flightSummaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 8,
  },
  flightNumberRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    gap: 8,
  },
  flightSummaryRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
    gap: 10,
  },
  flightNumber: {
    color: '#303030',
    fontSize: 28,
    lineHeight: 30,
    fontWeight: 700,
  },
  badgeText: {
    color: '#070B64',
    fontSize: 14,
    fontWeight: 700,
  },
  dateBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#E7E8FD',
  },
  dateBadgeText: {
    color: '#070B64',
    fontWeight: 700,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
    flexShrink: 0,
  },
  softBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#FDF0E7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  neutralBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#E7E8FD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxValue: {
    color: '#303030',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'right',
    fontWeight: 700,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
    paddingTop: 24,
  },
  statsLeft: {
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    flexGrow: 0,
    flexShrink: 1,
    gap: 14,
  },
  statsRight: {
    flexDirection: 'row',
    alignItems: 'stretch',
    flexShrink: 0,
    gap: 10,
    marginLeft: 'auto',
  },
  statColumn: {
    minWidth: 58,
    gap: 4,
  },
  statLabel: {
    color: '#404040',
    fontSize: 14,
    lineHeight: 13,
  },
  statValue: {
    color: '#303030',
    fontSize: 28,
    lineHeight: 30,
    fontWeight: 700,
  },
  statDivider: {
    width: 1,
    backgroundColor: '#dddddd',
  },
  statusBadge: {
    alignSelf: 'center',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#d0d0d0',
  },
  statusBadgeText: {
    color: '#303030',
    fontSize: 15,
    lineHeight: 18,
  },
  actionColumn: {
    width: 104,
    alignItems: 'flex-end',
    gap: 4,
  },
  statLabelRight: {
    textAlign: 'right',
  },
  statValueRight: {
    textAlign: 'right',
  },
  tatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
    backgroundColor: '#f7f7f7',
  },
  tatLabel: {
    color: '#303030',
    fontSize: 16,
    fontStyle: 'bold',
    fontWeight: 700,
  },
  tatValue: {
    color: '#303030',
    fontSize: 32,
    fontWeight: 700,
    fontStyle: 'bold',
  },
  cargoSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoTitle: {
    color: '#303030',
    fontSize: 16,
  },
  cargoMainRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  cargoMainCard: {
    flex: 1,
    padding: 16,
  },
  cargoMainCardBorder: {
    borderRightWidth: 1,
    borderRightColor: '#d9d9d9',
  },
  cargoCardLabel: {
    color: '#303030',
    fontSize: 12,
    marginBottom: 12,
  },
  cargoValuePill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#efefef',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cargoValueText: {
    color: '#303030',
    fontSize: 22,
  },
  cargoSpecialRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  cargoSpecialItem: {
    width: '47%',
  },
  cargoSpecialLabel: {
    color: '#4a4a4a',
    fontSize: 11,
    marginBottom: 8,
  },
  cargoSpecialValue: {
    alignSelf: 'flex-start',
    backgroundColor: '#efefef',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  cargoSpecialValueText: {
    color: '#303030',
    fontSize: 18,
  },
  footerActions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  footerButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 56,
    borderRadius: 8,
    borderWidth: 2,
  },
  footerButtonSecondary: {
    borderColor: '#2c31c9',
    backgroundColor: '#ffffff',
  },
  footerButtonPrimary: {
    borderColor: '#2c31c9',
    backgroundColor: '#2c31c9',
  },
  mainPanel: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 12,
  },
  topPanel: {
    paddingHorizontal: 24,
    backgroundColor: '#ffffff',
    borderBottom: '2px solid #D9D9D9',
    marginBottom: 24
  },
  taskControlsSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d9d9d9',
  },
  toolbar: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 16,
  },
  searchField: {
    flex: 1,
    minHeight: 64,
    borderWidth: 1,
    borderColor: '#bdbdbd',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 18,
    lineHeight: 22,
    color: '#303030',
    paddingVertical: 0,
  },
  toolbarButton: {
    minWidth: 168,
    minHeight: 64,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    backgroundColor: '#2c31c9',
  },
  reloadButton: {
    width: 64,
    minHeight: 64,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2c31c9',
    backgroundColor: '#ffffff',
  },
  categoryRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 16,
  },
  categoryButton: {
    flex: 1,
    minHeight: 66,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F2F2',
    paddingHorizontal: 18,
  },
  categoryButtonActive: {
    backgroundColor: '#2c31c9',
  },
  toolbarButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  categoryButtonText: {
    fontSize: 18,
    lineHeight: 22,
  },
  taskScroll: {
    flex: 1,
    paddingHorizontal: 24
  },
  taskListContent: {
    gap: 16,
    paddingBottom: 20,
  },
  taskCard: {
    borderWidth: 1,
    borderColor: '#d2d2d2',
    borderRadius: 20,
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 24,
  },
  taskCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  taskTitle: {
    flex: 1,
    color: '#303030',
    fontWeight: 700,
    fontStyle: 'bold',
    marginRight: 12,
    fontSize: 30
  },
  taskHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 0,
  },
  taskEditButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBadgeCompleted: {
    backgroundColor: '#d7f0ef',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  statusBadgeCompletedText: {
    color: '#07605B',
    fontWeight: '700',
    fontSize: 13,
  },
  statusBadgeInProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#d4edda',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  statusBadgeInProgressText: {
    color: '#1a6b3c',
    fontWeight: '700',
    fontSize: 13,
  },
  taskActionRow: {
    marginTop: 16,
  },
  taskActionBtn: {
    minHeight: 56,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  taskActionBtnTerminar: {
    backgroundColor: '#c4073f',
  },
  taskActionBtnComecar: {
    backgroundColor: '#2c31c9',
  },
  taskActionBtnFinalizado: {
    minHeight: 56,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#d7f0ef',
  },
  taskActionBtnFinalizadoText: {
    color: '#07605B',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  taskActionBtnDisabled: {
    opacity: 0.55,
  },
  taskActionBtnText: {
    color: '#ffffff',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  reloadButtonMobile: {
    width: 56,
    minHeight: 56,
  },
  taskMetricsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  taskBodyRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 16,
  },
  taskMetricsSummary: {
    flex: 1,
    justifyContent: 'center',
  },
  taskMetric: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  taskMetricWide: {
    flex: 1.02,
    minWidth: 104,
    paddingHorizontal: 10,
  },
  taskMetricDivider: {
    width: 1,
    backgroundColor: '#d9d9d9',
    marginVertical: 4,
  },
  taskMetricValue: {
    color: '#303030',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: 700,
    fontStyle: 'bold',
    marginBottom: 6,
  },
  taskMetricValueWide: {
    width: '100%',
    textAlign: 'center',
  },
  taskMetricLabel: {
    color: '#303030',
    lineHeight: 14,
    textAlign: 'center',
  },
  taskMetricLabelSingleLine: {
    width: '100%',
    fontSize: 12,
    lineHeight: 14,
  },
  taskActionWrap: {
    width: 210,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 4,
  },
  taskAction: {
    width: '100%',
    minHeight: 52,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  taskActionCompleted: {
    backgroundColor: '#d7f0ef',
  },
  taskActionInProgressWrap: {
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 228,
  },
  taskActionInProgressBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#d4edda',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  inProgressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1a6b3c',
  },
  taskActionTerminar: {
    backgroundColor: '#c4073f',
    minWidth: 228,
    minHeight: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  taskActionInProgress: {
    backgroundColor: '#c4073f',
  },
  taskActionPending: {
    backgroundColor: '#2c31c9',
  },
  taskActionText: {
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
  taskEditModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  taskEditModalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(21, 29, 47, 0.38)',
  },
  taskEditModalCard: {
    width: '78%',
    maxWidth: 920,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 24,
  },
  taskEditModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  taskEditModalTitle: {
    color: '#0a0e80',
    fontSize: 34,
    lineHeight: 38,
  },
  taskEditModalCloseButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskEditModalTimeRow: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 16,
  },
  taskEditModalField: {
    flex: 1,
    gap: 8,
  },
  taskEditModalFieldLabel: {
    color: '#4a4a4a',
    fontSize: 18,
    lineHeight: 24,
  },
  taskEditModalInput: {
    minHeight: 64,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
  },
  taskEditModalCommentInput: {
    minHeight: 150,
    borderWidth: 1,
    borderColor: '#8d8d8d',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    fontSize: 18,
    lineHeight: 24,
    color: '#303030',
    marginBottom: 12,
  },
  taskEditModalErrorText: {
    color: '#a60f0f',
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 10,
  },
  taskEditModalDivider: {
    height: 1,
    backgroundColor: '#d9d9d9',
    marginBottom: 18,
  },
  taskEditModalRestartButton: {
    minHeight: 62,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    backgroundColor: '#c4073f',
    marginBottom: 16,
  },
  taskEditModalRestartButtonText: {
    color: '#ffffff',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
  taskEditModalFooter: {
    flexDirection: 'row',
    gap: 16,
  },
  taskEditModalCancelButton: {
    flex: 1,
    minHeight: 62,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#c4073f',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
  },
  taskEditModalCancelButtonText: {
    color: '#c4073f',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
  taskEditModalSubmitButton: {
    flex: 1,
    minHeight: 62,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2c31c9',
    paddingHorizontal: 24,
  },
  taskEditModalSubmitButtonDisabled: {
    opacity: 0.55,
  },
  taskEditModalSubmitButtonText: {
    color: '#ffffff',
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
  detailMessage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailMessageCard: {
    padding: 24,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9d9d9',
  },
  detailMessageText: {
    fontSize: 18,
    lineHeight: 24,
  },
} as const;
