export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRightWidth: 1,
    overflow: 'hidden' as const,
  },
  headerBar: {
    height: 84,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  headerTitle: {
    color: '#303030',
    fontSize: 28,
  },
  searchBlock: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    gap: 12,
    borderBottomWidth: 1,
  },
  searchField: {
    minHeight: 56,
    borderWidth: 1,
    borderRadius: 8,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  searchInput: {
    flex: 1,
    color: '#303030',
    fontSize: 20,
    paddingVertical: 0,
  },
  orderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  orderLabel: {
    color: '#626262',
    fontSize: 16,
  },
  orderChips: {
    flexDirection: 'row' as const,
    gap: 12,
  },
  orderChip: {
    minHeight: 56,
    minWidth: 112,
    borderRadius: 999,
    paddingHorizontal: 20,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
  },
  orderChipActive: {
    backgroundColor: '#2c31c9',
  },
  orderChipIdle: {
    backgroundColor: '#efefef',
  },
  orderChipText: {
    fontSize: 18,
  },
  body: {
    flex: 1,
    minHeight: 0,
  },
  listScroll: {
    flex: 1,
  },
  listScrollContent: {
    paddingBottom: 16,
    backgroundColor: '#ffffff',
  },
  sectionBlock: {
    backgroundColor: '#ffffff',
  },
  sectionHeader: {
    minHeight: 58,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sectionHeaderLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  sectionHeaderRight: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  sectionCount: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: 8,
    borderRadius: 999,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 22,
  },
  sectionCountText: {
    fontSize: 16,
    lineHeight: 20,
  },
  sectionFlights: {
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  emptySection: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 24,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 24,
  },
  itemPressable: {
    width: '100%',
  },
  itemCard: {
    minHeight: 92,
    flexDirection: 'row' as const,
    borderRadius: 10,
    overflow: 'hidden' as const,
    backgroundColor: '#ffffff',
  },
  itemStatusBar: {
    width: 8,
    height: '100%',
  },
  itemContent: {
    flex: 1,
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  itemLeft: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'space-between' as const,
  },
  itemNumberRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    flexWrap: 'wrap' as const,
  },
  itemConnectionRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  itemRight: {
    width: 156,
    alignItems: 'flex-end' as const,
    justifyContent: 'space-between' as const,
  },
  itemTopBadges: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  itemAircraftTag: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderWidth: 2,
    borderRadius: 5,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#ffffff',
  },
  itemPriorityTag: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  itemFlightNumber: {
    fontSize: 22,
    lineHeight: 26,
  },
  itemAirportCode: {
    fontSize: 16,
    lineHeight: 20,
  },
  itemConnectionText: {
    fontSize: 15,
    lineHeight: 18,
  },
  itemAircraftTagText: {
    fontSize: 14,
    lineHeight: 18,
  },
  itemPriorityTagText: {
    fontSize: 17,
    lineHeight: 20,
  },
  itemScheduleText: {
    fontSize: 15,
    lineHeight: 18,
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    backgroundColor: '#ffffff',
  },
  footerButton: {
    minHeight: 64,
    borderWidth: 2,
    borderRadius: 8,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#ffffff',
  },
} as const;
